### ISSUE TITLE
Changing `spoke_role_arn` to another value doesn't actually work with IAMbic

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#381]
**Describe the bug**
I attempt to modify the value of `spoke_role_arn` to a custom value in the IAMbic config file. However, IAMbic doesn't actually quite work because it's expecting it to be a constant: https://github.com/noqdev/iambic/blob/eb9a41837d65c9e55b2c99ed800b6f898f6e6289/iambic/plugins/v0_1_0/aws/models.py#LL51C1-L51C1

**To Reproduce**
1. Create MyLeetSpokeRole across all accounts in AWS org.
2. Change IAMbic config file to use MyLeetSpokeRole instead of IambicSpokeRole
3. Run `iambic setup`
4. The wizard will have problem creating secret in the AWS setup

**Expected behavior**
If spoke_role_arn is available on config, it seems reason I can configure it. 

**Additional context**
The config file I am customizing

```
template_type: NOQ::Core::Config
version: '1'
aws:
  accounts:
    - account_id: '192455039954'
      account_name: iambic_test_spoke_account_2
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::192455039954:role/MyLeetSpokeRole
    - account_id: '333972133479'
      account_name: iambic_test_spoke_account_3
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::333972133479:role/MyLeetSpokeRole
    - account_id: '442632209887'
      account_name: iambic_test_spoke_account_1
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::442632209887:role/MyLeetSpokeRole
    - account_id: '580605962305'
      account_name: iambic_test_org_account
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::580605962305:role/MyLeetSpokeRole
  organizations:
    - aws_profile: iambic_test_org_account/iambic_test_org_account_admin
      default_rule:
        iambic_managed: read_and_write
      hub_role_arn: arn:aws:iam::580605962305:role/MyLeetHubRole
      identity_center:
        region: us-east-1
      org_account_id: '580605962305'
      org_id: o-8t0mt0ybdd
extends:
  - assume_role_arn: arn:aws:iam::580605962305:role/MyLeetSpokeRole
    key: AWS_SECRETS_MANAGER
    value: arn:aws:secretsmanager:us-east-1:580605962305:secret:iambic-config-secrets-foo
```
