### ISSUE TITLE
YAML Comments not attached to a node crashed IAMbic

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#396]
**Describe the bug**

This template crashed IAMbic due to the legit YAML comments not attached to a particular node

```
template_type: NOQ::AWS::IAM::Role
included_accounts:
  # You will need to replace the "NAME_OF_AWS_ACCOUNT_THAT_HAS_IambicHubRole"
  # with the account name of the AWS account holding the IambicHubRole.
  # In the event you change the secret names, you need to update those values as well.
  - NAME_OF_AWS_ACCOUNT_THAT_HAS_IambicHubRole
identifier: iambic_github_app_lambda_execution
properties:
  description: Github App Lambda Execution
  assume_role_policy_document:
    statement:
      - action: sts:AssumeRole
        effect: Allow
        principal:
          service: lambda.amazonaws.com
    version: '2012-10-17'
  inline_policies:
    - policy_name: github-app
      statement:
        - action:
            - logs:CreateLogGroup
          effect: Allow
          resource:
            - arn:aws:logs:*:{{var.account_id}}:log-group:*:log-stream:
          sid: CreateLogGroup
        - action:
            - secretsmanager:GetSecretValue
          effect: Allow
          resource:
            - arn:aws:secretsmanager:*:{{var.account_id}}:secret:iambic/github-app-private-key
            - arn:aws:secretsmanager:*:{{var.account_id}}:secret:iambic/github-app-private-key-*
            - arn:aws:secretsmanager:*:{{var.account_id}}:secret:iambic/github-app-webhook-secret
            - arn:aws:secretsmanager:*:{{var.account_id}}:secret:iambic/github-app-webhook-secret-*
          sid: SecretReading
        - action:
            - logs:CreateLogStream
            - logs:PutLogEvents
          effect: Allow
          resource:
            - arn:aws:logs:*:{{var.account_id}}:log-group:/aws/lambda/iambic_github_app_webhook*:*
          sid: LogEvents
        - action: sts:AssumeRole
          effect: Allow
          resource: arn:aws:iam::{{var.account_id}}:role/IambicHubRole
      version: '2012-10-17'
  role_name: iambic_github_app_lambda_execution
```

**To Reproduce**
1. Place the above template in the template directory
2. run `iambic plan <file>
3. IAMbic crash

**Expected behavior**
Legit YAML comments should not crash IAMbic

**Screenshots**
```
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/stevenmoy/noqdev/iambic/iambic/core/parser.py", line 82, in load_template
    template_dict = transform_comments(yaml.load(open(template_path)))
  File "/Users/stevenmoy/noqdev/iambic/iambic/core/utils.py", line 336, in transform_comments
    comment_dict[key] = comment[2].value
AttributeError: 'NoneType' object has no attribute 'value'
"""
```

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (22E261)
 - IAMbic version 0.7.1

**Additional context**
N/A
