### ISSUE TITLE
Support ignoring resources by tag or name to prevent IAMbic from syncing these resources

### ISSUE THREAD

**Issue by castrapel** [noqdev/iambic#421]
**Is your feature request related to a problem? Please describe.**
Problem: I do not want IAMbic to sync AWS managed roles (Such as AWS SSO Roles), CDK/cloudformation managed resources, or other roles. 

**Describe the solution you'd like**
I would like a configuration option that instructs IAMbic to ignore resources based on:

- Resource Name
- Resource Path (Such as an IAM Role path)
- Existence of matching Resource Tag Key
- Existence of matching Resource Tag Key/Value

**Community Engagement**
Help us prioritize this request and express your support by adding a 👍 reaction to the original issue. This will assist both the community and the maintainers in addressing this request.

Please avoid leaving "+1" or "me too" comments as they create extra noise for issue followers and do not assist in prioritizing the request. If you are considering working on this issue or have already submitted a pull request, kindly leave a comment.

**Comment by castrapel** [comment]
CC @datfinesoul

**Comment by datfinesoul** [comment]
After #388 is implemented it will be easier to provide more detailed feedback as to how this would be useful.  IMO would be worth holding off until that one is done.

**Comment by castrapel** [comment]
Another option we discussed [in Slack](https://noqcommunity.slack.com/archives/C052R22L3C6/p1686906565543649) 
(Join [here](https://communityinviter.com/apps/noqcommunity/noq)) is a configuration specific to a provider. This would be an easier change because the AWS configuration is already passed around.

```yaml
import_rules:
  - match_tags:
      - key: terraform
        # optional `value` field
    action: iambic_managed.import_only
  - match_names:
      - "AWS SSO Role*"
      - "CDK*"
      - "CloudFormation*"
    action: ignore
  - match_paths:
      - "/service-role/*"
    action: ignore
  - match_tags:
      - key: "ManagedBy"
        value: "CDK"
    action: ignore
  - match_template_types:
      - "NOQ::AWS::IAM::ManagedPolicy"
    action: iambic_managed.import_only
```
