### ISSUE TITLE
[docs] schema docs generation should use the snake_case to avoid confusion

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#475]
**Describe the bug**
An [example](https://docs.iambic.org/reference/schemas/aws_iam_role_template) reference elements using UpperCamelCase when the official examples use snake_case in template definition. 

Docs: 

```
Definitions

IambicManaged: An enumeration. Must be one of: ["undefined", "read_and_write", "import_only", "enforced", "disabled"].
```

Template Defintiion:

[Link](https://docs.iambic.org/how_to_guides/prevent-drift#example-use-cases)

```
template_type: NOQ::Okta::Group
iambic_managed: enforced
idp_name: development
properties:
  name: cloud_admins
  description: Cloud Administrators
  members:
    - username: user1@example.com
    - username: user2@example.com
```

**To Reproduce**

1. Check above reference docs vs template.

**Expected behavior**
Official docs should use snake_case in docs generation.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.
