### ISSUE TITLE
Diff appears to wrongly show removal of some entities

### ISSUE THREAD

**Issue by debedb** [noqdev/iambic#480]
I have a group template for Okta like so

```
template_type: NOQ::Okta::Group
idp_name: noq-dev
properties:
  name: greg-test-group
  group_id: XYZ
  members:
    - username: greg.rule.1@noq.dev
    - username: greg@noq.dev
```

This currently corresponds to the membership of the group in Okta.
I am now going to add to it a new user (keeping the others as is):
```
- username: greg2.noq.dev
```

And run `iambic apply`. I see the following:

```
Attach
└── /Users/greg/git/iambic-templates-greg-orig/resources/okta/group/noq-dev/greg-test-group.yaml
    └── noq-dev
        └── okta:group // 00gdglbcs4CiEbMsU4x7
            └── users:
                -(From)
                "greg@noq.dev"
                +(To)
                "greg2@noq.dev"users:
                -(Remove)
                [
                  "greg.rule.1@noq.dev"
                ]
```

The emails in the "Remove" section have not actually been removed from the template, and are not removed when the actual action proceeds. Looks like just the diff is wrong as displayed.
