### ISSUE TITLE
NOQ::AWS::Organizations::SCP Filter does not work

### ISSUE THREAD

**Issue by rodolphoescobar** [noqdev/iambic#608]
**Describe the bug**
Filter via match_template_types for NOQ::AWS::Organizations::SCP is not applied during iambic import. All other types work fine.

**iambic_config.yaml**
```
template_type: NOQ::Core::Config
version: 0.11.59
aws:
  import_rules:
      - action: ignore
        match_template_types:
          - NOQ::AWS::IAM::Group
          - NOQ::AWS::IAM::ManagedPolicy
          - NOQ::AWS::IAM::Role
          - NOQ::AWS::IAM::User
          - NOQ::AWS::Organizations::SCP
```
